[package]
name = "MPC-Research-Project"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
rand = { version = "0.8.5", features = ["small_rng"] }
plotly = "0.10.0"
rand_seeder = "0.3.0"
